name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo "%gv^$YDg9JjC" | docker login -u "choyce" --password-stdin
        docker image build -t choyce/dm-api:latest .
        docker push choyce/dm-api:latest